services:
  postgres:
    build:
      context: .
      dockerfile: PG_Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: album
  album-ai:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./images:/home/images

