services:
  postgres:
    build:
      context: .
      dockerfile: PG_Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: album

  album-ai:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=album
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - SERVER_PORT=8080
      - SIMILARITY_SCORE=0.8
      - MAX_SEARCH_LIMIT=10
      - IMAGE_EXTRACT_PROVIDER=openai
      - IMAGE_EXTRACT_PROVIDER_MODEL=gpt-4o-mini
      - EMBEDDING_PROVIDER=openai
      - EMBEDDING_PROVIDER_MODEL=text-embedding-3-large
      - CHAT_PROVIDER=openai
      - CHAT_PROVIDER_MODEL=gpt-4o-mini
    volumes:
      - ./images:/home/images

