services:
  album-ai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=album
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./images:/home/images

