services:
  album-ai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./images:/home/images

