services:
  postgres:
    build:
      context: .
      dockerfile: PG_Dockerfile
    ports:
      - "5432:5432"
  album-ai:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./images:/home/images

