services:
  album-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=album
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - SIMILARITY_SCORE=0.8
      - MAX_SEARCH_LIMIT=10
      - IMAGE_EXTRACT_PROVIDER=openai
      - IMAGE_EXTRACT_PROVIDER_MODEL=gpt-4o-mini
      - EMBEDDING_PROVIDER=openai
      - EMBEDDING_PROVIDER_MODEL=text-embedding-3-large
      - CHAT_PROVIDER=openai
      - CHAT_PROVIDER_MODEL=gpt-4o-mini
    volumes:
      - ./images:/home/images

